// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txqgsdohtnljqfgsjmss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4cWdzZG9odG5sanFmZ3NqbXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTAwODYsImV4cCI6MjA3Mzk2NjA4Nn0.TFIO5BXx8A49g1nMCZ8v3izhyN4i7oQrLp528Kuefh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});