// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://schyaoiwyzpnkpakxewx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjaHlhb2l3eXpwbmtwYWt4ZXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODYxMTgsImV4cCI6MjA3NDI2MjExOH0.zA1pbRdYYBQY3j15jF5R-nY40NtXSpU9LsECpPknB8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});